# Generated by Django 2.1.7 on 2019-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('path', models.CharField(max_length=100, verbose_name='图片路径')),
                ('link', models.CharField(max_length=100, verbose_name='链接路径')),
                ('content', models.CharField(max_length=50, verbose_name='介绍')),
                ('content1', models.CharField(max_length=50, verbose_name='介绍_1')),
            ],
        ),
        migrations.CreateModel(
            name='DemandTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('style', models.CharField(max_length=20, verbose_name='装修风格')),
                ('noodlesproduct', models.CharField(max_length=5, verbose_name='房屋面积')),
                ('demandtype', models.CharField(max_length=5, verbose_name='找谁装修')),
            ],
        ),
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True, verbose_name='评论时间')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Metamorphosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('titleImg', models.ImageField(blank=True, default='Null', null=True, upload_to='', verbose_name='首页图片')),
                ('titleTest', models.TextField(blank=True, default='Null', max_length=400, null=True, verbose_name='内容头部')),
                ('date', models.DateField(null=True, verbose_name='创建日期')),
                ('titleImg1', models.ImageField(blank=True, default='Null', null=True, upload_to='', verbose_name='图片_1')),
                ('titleTest1', models.TextField(blank=True, default='Null', max_length=400, null=True, verbose_name='内容_1')),
                ('titleImg2', models.ImageField(blank=True, default='Null', null=True, upload_to='', verbose_name='图片_2')),
                ('titleTest2', models.TextField(blank=True, default='Null', max_length=400, null=True, verbose_name='内容_2')),
                ('titleImg3', models.ImageField(blank=True, default='Null', null=True, upload_to='', verbose_name='图片_3')),
                ('titleTest3', models.TextField(blank=True, default='Null', max_length=400, null=True, verbose_name='内容_3')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('path', models.CharField(max_length=100, verbose_name='图片路径')),
                ('path1', models.CharField(max_length=100, verbose_name='图片路径_1')),
                ('path2', models.CharField(max_length=100, verbose_name='图片路径_2')),
                ('specifications', models.CharField(max_length=20, verbose_name='规格')),
                ('price', models.CharField(max_length=20, verbose_name='价钱')),
                ('discount', models.CharField(max_length=20, verbose_name='打折后')),
                ('sketch', models.CharField(max_length=50, verbose_name='简述')),
                ('briefintroduction', models.TextField(max_length=100, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类型名称')),
                ('path', models.CharField(max_length=100, verbose_name='图片路径')),
                ('product_relationship', models.ManyToManyField(to='OfficialWebsite.ProductCenter')),
            ],
        ),
    ]
